// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © redshad0ww

//@version=5
indicator("Moonkin Bars", overlay = true, precision = 2)
import redshad0ww/MoonkinLibs/4 as moonkinLibs

var inputIndicator = input.string("mfi", options = ["mfi", "rsi"])
var inputSrc = input.string("hlc3", options = ["hlc3", "close", "ohlc"])

src = switch inputSrc
    "hlc3" => (hlc3)
    "close" => (close)
    "ohlc" => (ohlc4)
    => (hlc3)

base = switch inputIndicator
    "mfi" => ta.mfi(src,14)
    "rsi" => ta.rsi(src,14)

getRainbowColor(series float rsiValue) =>
    switch
        rsiValue < 35 => color.from_gradient(rsiValue, 20, 32, color.rgb(255, 0, 0), color.rgb(255, 80, 0)) 
        rsiValue < 40 => color.from_gradient(rsiValue, 32, 40, color.rgb(255, 80, 0), color.rgb(255, 255, 0)) 
        rsiValue < 50 => color.from_gradient(rsiValue, 40, 50, color.rgb(255, 255, 0), color.rgb(255, 255, 255)) 
        rsiValue < 70 => color.from_gradient(rsiValue, 50, 60, color.rgb(255, 255, 255), color.rgb(75, 255, 255)) 
        =>               color.from_gradient(rsiValue, 70, 90, color.rgb(75, 255, 225), color.rgb(255, 0, 255)) 
        
plotColor = getRainbowColor(base)
plotcandle(open, high, low, close, color = plotColor, wickcolor = plotColor, bordercolor = plotColor, editable = false, title = "Rainbow Bars", display = display.pane)

//RSI 
var useRsi = input.bool(true, "Use Rsi", group = "Controls")

rsi = ta.rsi(close, 14)
rsiColor = moonkinLibs.getRainbowColorCustom(rsi, 2, color.rgb(255, 60, 60), color.rgb(255, 255, 255), 10, 35) //This is bugged causing colors not to be editable in the gui
plotchar(useRsi and (rsi > 75 ? rsi : na), title = "Rsi Print", color = rsiColor, char = "x", size=size.tiny)
plotchar(useRsi and (rsi < 35 ? rsi : na), title = "Rsi Print", color = rsiColor, char = "x", size=size.tiny, location = location.belowbar)

//RSI 

